name = "SurfaceFluxes"
uuid = "49b00bb7-8bd4-4f2b-b78c-51cd0450215f"
authors = ["Climate Modeling Alliance"]
version = "0.12.0"

[deps]
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"

[weakdeps]
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"

[extensions]
CreateParametersExt = "ClimaParams"

[compat]
ClimaParams = "0.10"
DocStringExtensions = "0.8, 0.9"
RootSolvers = "0.4"
Thermodynamics = "0.12.8"
julia = "1.9"
