agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.9.3 cuda/11.8 ucx/1.14.1_cuda-11.8 openmpi/4.1.5_cuda-11.8 hdf5/1.12.2-ompi415 nsight-systems/2023.2.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_CPU_TARGET: 'broadwell;skylake'


steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(); '"

    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "init gpu env"
    key: "init_gpu_env"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project=test/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(); '"
      - "julia --project=test/ -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.status()'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - wait

  - label: "CPU tests"
    command:
      - "julia --project=test --color=yes test/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "GPU tests"
    command:
      - "julia --project=test --color=yes test/runtests_gpu.jl"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

