env:
  JULIA_VERSION: "1.7.0"
  CUDA_VERSION: "10.2"

steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project=test/ -e 'using Pkg; Pkg.add(PackageSpec(name=\"Thermodynamics\", rev=\"orad/refactor-parameters-v1b\"))'"
      - "julia --project=test/ -e 'using Pkg; Pkg.add(PackageSpec(name=\"CLIMAParameters\", rev=\"orad/refactor-parameters-v2b\"))'"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path = \".\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "init gpu env"
    key: "init_gpu_env"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project=test/ -e 'using Pkg; Pkg.add(PackageSpec(name=\"Thermodynamics\", rev=\"orad/refactor-parameters-v1b\"))'"
      - "julia --project=test/ -e 'using Pkg; Pkg.add(PackageSpec(name=\"CLIMAParameters\", rev=\"orad/refactor-parameters-v2b\"))'"
      - "julia --project=test/ -e 'using Pkg; Pkg.develop(path = \".\")'"
      - "julia --project=test/ -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test/ -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.add(\"CUDA\")'"
      - "julia --project=test/ -e 'using CUDA; CUDA.versioninfo()'"
      - "julia --project=test/ -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project=test/ -e 'using Pkg; Pkg.status()'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - wait

  - label: "CPU tests"
    command:
      - "julia --project=test test/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "GPU tests"
    command:
      - "julia --project=test test/runtests.jl CuArray"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

